// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vies.Core.Database.Data;

namespace Vies.Core.Database.Migrations
{
    [DbContext(typeof(ViesCoreDatabaseContext))]
    [Migration("20201222194832_2")]
    partial class _2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Vies.Core.Models.CheckVat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("Address");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("DateOfCreate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("DateOfCreate")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DateOfModification")
                        .HasColumnType("datetime")
                        .HasColumnName("DateOfModification");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime")
                        .HasColumnName("RequestDate");

                    b.Property<string>("UniqueIdentifierOfTheLoggedInUser")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("UniqueIdentifierOfTheLoggedInUser");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit")
                        .HasColumnName("Valid");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("VatNumber");

                    b.HasKey("Id");

                    b.HasIndex("DateOfCreate")
                        .HasDatabaseName("IX_CheckVatDateOfCreate");

                    b.HasIndex("DateOfModification")
                        .HasDatabaseName("IX_CheckVatDateOfModification");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_CheckVatId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_CheckVatName");

                    b.HasIndex("RequestDate")
                        .HasDatabaseName("IX_CheckVatRequestDate");

                    b.HasIndex("UniqueIdentifierOfTheLoggedInUser")
                        .HasDatabaseName("IX_CheckVatUniqueIdentifierOfTheLoggedInUser");

                    b.HasIndex("VatNumber")
                        .HasDatabaseName("IX_CheckVatNumber");

                    b.ToTable("CheckVat", "etvc");
                });
#pragma warning restore 612, 618
        }
    }
}
